//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.AppConnect
{
    using System;
    using System.Collections.Generic;

    public partial class Client
    {
        public int id { get; set; }
        public string lName { get; set; }
        public string fName { get; set; }
        public string mName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int subscription { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int trainer { get; set; }

        public virtual Subscription Subscription1 { get; set; }
        public virtual Trainer Trainer1 { get; set; }

        public System.TimeSpan CorrectDate
        {
            get { return dateEnd - DateTime.Today; }
        }

    }
}